name: Build Build Bro UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:

    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm run start-iso
          build: npm run build
