name: Build Build Bro UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Maria DB
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'buildz'
          mysql user: 'buildz'
          mysql password: 'buildz'
          character set server: 'utf8'
          collation server: 'utf8_general_ci'

      - name: Boot Build Bruh API
        uses: cyrusroshan/generic-docker-run@main
        with:
          command: "docker run -d --rm -p 8080:8085 --name build-bro-api esistegalaber/build-bruh-api:0.1.0"

      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          build: npm run build

      - name: Cypress run
        container: cypress/browsers:node18.12.0-chrome106-ff106
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm run start
          build: npm run build

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
